CREATE TABLE BRONEERING (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    LAUD INTEGER NOT NULL,
    NIMI VARCHAR(255) NOT NULL,
    AEG TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE LAUD (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    BRONNITUD TIMESTAMP,
    PRIVAATNE INTEGER NOT NULL,
    AKNA_KOHT INTEGER NOT NULL,
    LIGIPÄÄSETAVUS INTEGER NOT NULL,
    INIMESTE_ARV INTEGER NOT NULL,
    TSOON VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);